export const tasksTypes = {
  ADD_TASK: 'ADD_TASK',
  DELETE_TASK: 'DELETE_TASK',
  ADD_TASK_TO_SELECTED_TASKS: 'ADD_TASK_TO_SELECTED_TASKS',
  DELETE_ALL_SELECTED_TASKS: 'DELETE_ALL_SELECTED_TASKS',
  DELETE_ALL: 'DELETE_ALL',
  SET_TASK: 'SET_TASK',
  SET_TASKS: 'SET_TASKS',
  SET_IMAGE: 'SET_IMAGE',
};